### PR TITLE
Add Traditional Chinese

### PR DESCRIPTION
**Pull request by XoF-eLtTiL**
Translated from the latest English file

### CODE REVIEW

**Comment by ChrisFeline** [comment]
Please next time, don't create a PR into main

**Comment by XoF-eLtTiL** [comment]
> Please next time, don't create a PR into main
Sorry. I'll take care of it next time.

**Comment by ChrisFeline** [comment]
No worries, thank you for your contribution. 🫶

**Comment by XoF-eLtTiL** [comment]
> No worries, thank you for your contribution. 🫶

Just a quick question.
Can Readme files be translated?

**Pull request merged**
