### PR TITLE
Update locale "en-US"

### PR DESCRIPTION
**Pull request by sageyx2002**
This fixes some grammatical errors and adds some minor changes for better clarity and readability to the "en-US" locale.

### CODE REVIEW

**Comment by ChrisFeline** [comment]
I will return to this one later, I have quite some progress in a local branch I haven't published yet.
It contains information about the upcoming update for Terrors of Nowhere so I am not allowed to publish for the time being.

I don't usually accept PR for grammar, but I will see if I can merge this with local changes.

**Comment by sageyx2002** [comment]
Take your time! These were just suggestions, feel free to reject :)

**Comment by ChrisFeline** [comment]
No worries, I am just a coward, and I am afraid of merging conflicts

**Comment by ChrisFeline** [comment]
Weather update, I might not be able to merge this specific request. But after the update, if you're still willing to help with grammar on the new `en-US.json` on a new request I will happily merge the updated file.

**Comment by sageyx2002** [comment]
Absolutely! Feel free to close this for the time being

**Comment by ChrisFeline** [comment]
Update is out!

**Pull request closed without merging**
